const palette = {
  red: '#C0392B',
  redLight: '#E74C3C',
  redDark: '#922B21',
  gold: '#F39C12',
  black: '#0A0A0A',
  gray900: '#1A1A1A',
  gray800: '#2D2D2D',
  gray700: '#404040',
  gray600: '#595959',
  gray400: '#9E9E9E',
  gray200: '#E0E0E0',
  gray100: '#F5F5F5',
  white: '#FFFFFF',
  green: '#27AE60',
  blue: '#2980B9',
};

export const Colors = {
  light: {
    primary: palette.red,
    primaryLight: palette.redLight,
    primaryDark: palette.redDark,
    accent: palette.gold,
    background: palette.white,
    surface: palette.gray100,
    surfaceElevated: palette.white,
    text: palette.black,
    textSecondary: palette.gray600,
    textMuted: palette.gray400,
    border: palette.gray200,
    borderStrong: palette.gray400,
    success: palette.green,
    info: palette.blue,
    tabBar: palette.white,
    tabBarActive: palette.red,
    tabBarInactive: palette.gray400,
  },
  dark: {
    primary: palette.redLight,
    primaryLight: palette.red,
    primaryDark: palette.redDark,
    accent: palette.gold,
    background: palette.black,
    surface: palette.gray900,
    surfaceElevated: palette.gray800,
    text: palette.white,
    textSecondary: palette.gray400,
    textMuted: palette.gray600,
    border: palette.gray800,
    borderStrong: palette.gray700,
    success: palette.green,
    info: palette.blue,
    tabBar: palette.gray900,
    tabBarActive: palette.redLight,
    tabBarInactive: palette.gray600,
  },
};

export type ColorScheme = typeof Colors.light;